# main text of home
name: M4e4 Window
bio: I'm floating in space

# twitter summary info
description: Stuff concerning Happy Normal
picture: assets/images/water.gif

url: http://koppl.in/violet
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
github: Heloise666
email: huenotelos@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
